app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect

db = SQLAlchemy()
csrf = CSRFProtect()


def create_app(config_filename="config.py"):
    """
    Create the Flask application.

    Parameters
    ----------
    config_filename : str
        The path to the configuration file.

    Returns
    -------
    app : Flask
        The Flask application.

    """
    
    app = Flask(__name__)

    app.config.from_pyfile(config_filename)

    db.init_app(app)
    csrf.init_app(app)

    from app.routes import main

    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template
from app.Controllers import (
    StudentController,
    TeacherController,
    DisciplineController,
    CourseController,
)

main = Blueprint("main", __name__)


@main.route("/", methods=["GET"])
def index():
    return render_template("nav.html")


@main.route("/students", methods=["GET"])
def student():
    return StudentController.index()


@main.route("/student/create", methods=["GET", "POST"])
def student_create():
    return StudentController.create()


@main.route("/student/edit/<int:id>", methods=["GET", "POST"])
def student_edit(id: int):
    return StudentController.edit(id)


@main.route("/student/destroy/<int:id>", methods=["GET", "POST"])
def student_destroy(id: int):
    return StudentController.destroy(id)


@main.route("/teachers", methods=["GET"])
def teacher():
    return TeacherController.index()


@main.route("/teacher/create", methods=["GET", "POST"])
def teacher_create():
    return TeacherController.create()


@main.route("/teacher/edit/<int:id>", methods=["GET", "POST"])
def teacher_edit(id: int):
    return TeacherController.edit(id)


@main.route("/teacher/destroy/<int:id>", methods=["GET", "POST"])
def teacher_destroy(id):
    return TeacherController.destroy(id)


@main.route("/disciplines", methods=["GET"])
def discipline():
    return DisciplineController.index()


@main.route("/discipline/create", methods=["GET", "POST"])
def discipline_create():
    return DisciplineController.create()


@main.route("/discipline/edit/<int:id>", methods=["GET", "POST"])
def discipline_edit(id: int):
    return DisciplineController.edit(id)


@main.route("/discipline/destroy/<int:id>", methods=["GET", "POST"])
def discipline_destroy(id: int):
    return DisciplineController.destroy(id)


@main.route("/courses", methods=["GET"])
def course():
    return CourseController.index()


@main.route("/course/create", methods=["GET", "POST"])
def course_create():
    return CourseController.create()


@main.route("/course/edit/<int:id>", methods=["GET", "POST"])
def course_edit(id: int):
    return CourseController.edit(id)


@main.route("/course/destroy/<int:id>", methods=["GET", "POST"])
def course_destroy(id: int):
    return CourseController.destroy(id)

app/templates/class.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Student</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

  <div class="container my-5">
    <a href="/">Back to home page</a>
    <form class="w-50 m-auto" method="POST" action="">
      {{ form.hidden_tag() }}

      <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {{ form.name(class="form-control", placeholder="Enter the class name") }}
      </div>

      <div class="mb-3">
        {{ form.code.label(class="form-label") }}
        {{ form.code(class="form-control", placeholder="Enter the class code") }}
      </div>

      <div class="mb-3">
        {{ form.discipline.label(class="form-label") }}
        {{ form.discipline(class="form-select") }}
      </div>

      <div class="mb-3">
        {{ form.teacher.label(class="form-label") }}
        {{ form.teacher(class="form-select") }}
      </div>

      <div class="d-grid">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="mt-3">
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <h2 class="mt-5 mb-3 text-center">Registered Classes</h2>
    <ul class="list-group">
      {% for class_ in classes %}
      <li class="list-group-item">{{ class_.name }}</li>
      {% endfor %}
    </ul>

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - School System</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/v/bs5/dt-2.2.1/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    <header class="container-fluid">
        <div class="px-3 py-2 border-bottom">
            <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-decoration-none">
                    <img src="{{ url_for('static', filename='img/ifms.png') }}" alt="IFMS Logo" width="60">
                </a>
                <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                    <li>
                        <a href="{{ url_for('main.index') }}" class="nav-link text-black">
                            <i class="bi bi-house mx-auto mb-1 fs-4"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.student') }}" class="nav-link text-primary">
                            <i class="bi bi-people mx-auto mb-1 fs-4"></i>
                            Students
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.teacher') }}" class="nav-link text-secondary">
                            <i class="bi bi-people mx-auto mb-1 fs-4"></i>
                            Teachers
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.discipline') }}" class="nav-link text-danger">
                            <i class="bi bi-book mx-auto mb-1 fs-4"></i>
                            Disciplines
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.course') }}" class="nav-link text-success">
                            <i class="bi bi-mortarboard mx-auto mb-1 fs-4"></i>
                            Courses
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="container">
        {% block content %}

        {% endblock %}
    </main>

    <!-- Toasts for messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="toast-container position-static"></div>
    {% for category, message in messages %}
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <i class="bi bi-exclamation-square-fill text-success me-2 fs-5"></i>
                <strong class="me-auto text-{{ category }} text-capitalize">{{ category }}</strong>
                <small>now</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js"
        integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/v/bs5/dt-2.2.1/datatables.min.js"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>

app/templates/nav.html
{% extends 'index.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="px-4 py-5 text-center">
    <img class="d-block mx-auto mb-4" src="{{ url_for('static', filename='img/ifms.png') }}" alt="IFMS Logo"
        width="100">
    <h1 class="display-5 fw-bold text-body-emphasis">School System</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">The school system developed in Python with Flask is a modern and efficient web application,
            designed to manage several essential functionalities of an educational institution. The main objective of
            the
            system is to facilitate the organization of information about students, teachers, classes and disciplines,
            offering an intuitive and responsive interface.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a type="button" href="{{ url_for('main.student') }}" class="btn btn-primary btn-lg px-4 gap-3">Students</a>
            <a type="button" href="{{ url_for('main.teacher') }}" class="btn btn-secondary btn-lg px-4">Teachers</a>
            <a type="button" href="{{ url_for('main.discipline') }}" class="btn btn-danger btn-lg px-4">Disciplines</a>
            <a type="button" href="{{ url_for('main.course') }}" class="btn btn-success btn-lg px-4">Courses</a>
        </div>
    </div>
</div>

{% endblock %}

app/templates/pages/course/create.html
{% extends 'index.html' %}

{% block title %}Courses{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.course') }}" class="btn btn-secondary btn-sm">Back courses</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Edit a course</h2>

    <form class="w-50 m-auto" method="POST" action="{{ url_for('main.course_create') }}" novalidate>
        {{ form.hidden_tag() }}

        {% include 'pages/course/form.html' %}

    </form>
</div>

{% endblock %}

app/templates/pages/course/edit.html
{% extends 'index.html' %}

{% block title %}Courses{% endblock %}

{% block content %}

<div class="my-5">
  {% include 'pages/course/form.html' %}
</div>


{% endblock %}

app/templates/pages/course/form.html
<div class="mb-3">
    {{ form.name.label(class="form-label") }}
    {% if form.name.errors %}
    {{ form.name(class="form-control is-invalid", placeholder="Enter the course name") }}
    {% for error in form.name.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    {% else %}
    {{ form.name(class="form-control", placeholder="Enter the course name") }}
    {% endif %}
</div>

<div class="mb-3">
    {{ form.code.label(class="form-label") }}
    {% if form.code.errors %}
    {{ form.code(class="form-control is-invalid", placeholder="Enter the course code") }}
    {% for error in form.code.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    {% else %}
    {{ form.code(class="form-control", placeholder="Enter the course code") }}
    {% endif %}
</div>

<div class="mb-3">
    {{ form.student.label(class="form-label") }}
    {% for subfield in form.student %}
    <div class="form-check">
        {{ subfield(class="form-check-input") }}
        {{ subfield.label(class="form-check-label") }}
    </div>
    {% endfor %}
</div>

<div class="mb-3">
    {{ form.teacher.label(class="form-label") }}
    {% for subfield in form.teacher %}
    <div class="form-check">
        {{ subfield(class="form-check-input") }}
        {{ subfield.label(class="form-check-label") }}
    </div>
    {% endfor %}
</div>

<div class="mb-3">
    {{ form.discipline.label(class="form-label") }}
    {% for subfield in form.discipline %}
    <div class="form-check">
        {{ subfield(class="form-check-input") }}
        {{ subfield.label(class="form-check-label") }}
    </div>
    {% endfor %}
</div>

<div class="d-grid">
    {{ form.submit(class="btn btn-primary") }}
</div>

app/templates/pages/course/index.html
{% extends 'index.html' %}

{% block title %}Courses{% endblock %}

{% block content %}

<div class="container my-5">

    <div class="d-grid gap-2 d-md-block">
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary btn-sm">Back home page</a>
        <a href="{{ url_for('main.course_create') }}" class="btn btn-primary btn-sm">Create a new course</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Registered courses</h2>

    <div class="table-responsive">
        <table id="table" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Code</th>
                    <th scope="col">Students</th>
                    <th scope="col">Teachers</th>
                    <th scope="col">Disciplines</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <th scope="row">{{ course.id }}</th>
                    <td>{{ course.name }}</td>
                    <td>{{ course.code }}</td>
                    <td>
                        {% if course.students|length == 0 %}
                        No students
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Students
                            </button>
                            <ul class="dropdown-menu">
                                {% for student in course.students %}
                                <li><a class="dropdown-item" href="#">{{ student.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        {% if course.teachers|length == 0 %}
                        No teachers
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Teachers
                            </button>
                            <ul class="dropdown-menu">
                                {% for teacher in course.teachers %}
                                <li><a class="dropdown-item" href="#">{{ teacher.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        {% if course.disciplines|length == 0 %}
                        No disciplines
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Disciplines
                            </button>
                            <ul class="dropdown-menu">
                                {% for discipline in course.disciplines %}
                                <li><a class="dropdown-item" href="#">{{ discipline.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('main.course_edit', id=course.id) }}"
                            class="btn btn-warning btn-sm float-end ms-2">Edit</a>
                    </td>
                    <td>
                        <a href="{{ url_for('main.course_destroy', id=course.id) }}"
                            class="btn btn-danger btn-sm float-end">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}

app/templates/pages/discipline/create.html
{% extends 'index.html' %}

{% block title %}Disciplines{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.discipline') }}" class="btn btn-secondary btn-sm">Back disciplines</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Edit a discipline</h2>

    <form class="w-50 m-auto" method="POST" action="{{ url_for('main.discipline_create') }}" novalidate>
        {{ form.hidden_tag() }}

        {% include 'pages/discipline/form.html' %}

    </form>
</div>

{% endblock %}

app/templates/pages/discipline/edit.html
{% extends 'index.html' %}

{% block title %}Disciplines{% endblock %}

{% block content %}

<div class="my-5">
  {% include 'pages/discipline/form.html' %}
</div>


{% endblock %}

app/templates/pages/discipline/index.html
{% extends 'index.html' %}

{% block title %}Disciplines{% endblock %}

{% block content %}

<div class="container my-5">

    <div class="d-grid gap-2 d-md-block">
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary btn-sm">Back home page</a>
        <a href="{{ url_for('main.discipline_create') }}" class="btn btn-primary btn-sm">Create a new discipline</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Registered Disciplines</h2>

    <div class="table-responsive">
        <table id="table" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Code</th>
                    <th scope="col">Workload</th>
                    <th scope="col">Teachers</th>
                    <th scope="col">Courses</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for discipline in disciplines %}
                <tr>
                    <th scope="row">{{ discipline.id }}</th>
                    <td>{{ discipline.name }}</td>
                    <td>{{ discipline.code }}</td>
                    <td>{{ discipline.workload }}</td>
                    <td>
                        {% if discipline.teachers|length == 0 %}
                        No teachers
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Teachers
                            </button>
                            <ul class="dropdown-menu">
                                {% for teacher in discipline.teachers %}
                                <li><a class="dropdown-item" href="#">{{ teacher.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        {% if discipline.courses|length == 0 %}
                        No courses
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Courses
                            </button>
                            <ul class="dropdown-menu">
                                {% for course in discipline.courses %}
                                <li><a class="dropdown-item" href="#">{{ course.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('main.discipline_edit', id=discipline.id) }}"
                            class="btn btn-warning btn-sm float-end ms-2">Edit</a>
                    </td>
                    <td>
                        <a href="{{ url_for('main.discipline_destroy', id=discipline.id) }}"
                            class="btn btn-danger btn-sm float-end">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/pages/student/create.html
{% extends 'index.html' %}

{% block title %}Students{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.student') }}" class="btn btn-secondary btn-sm">Back students</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Create a new student</h2>

    <form class="m-auto" method="POST" action="{{ url_for('main.student_create') }}" novalidate>
        {{ form.hidden_tag() }}

        {% include 'pages/student/form.html' %}

    </form>
</div>

{% endblock %}

app/templates/pages/student/edit.html
{% extends 'index.html' %}

{% block title %}Students{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.student') }}" class="btn btn-secondary btn-sm">Back students</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Edit a student</h2>

    <form class="m-auto" method="POST" action="{{ url_for('main.student_edit', id=student.id) }}" novalidate>

        {{ form.hidden_tag() }}

        {% include 'pages/student/form.html' %}

    </form>

</div>


{% endblock %}

app/templates/pages/student/index.html
{% extends 'index.html' %}

{% block title %}Students{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 d-md-block">
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary btn-sm">Back home page</a>
        <a href="{{ url_for('main.student_create') }}" class="btn btn-primary btn-sm">Create a new student</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Registered students</h2>

    <div class="table-responsive">
        <table id="table" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Registration</th>
                    <th scope="col">Date of birth</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Address</th>
                    <th scope="col">Phone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Course</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">{{ student.id }}</th>
                    <td>{{ student.name }}</td>
                    <td>{{ student.registration }}</td>
                    <td>{{ student.date_of_birth }}</td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.address }}</td>
                    <td>{{ student.phone }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.course.name }}</td>
                    <td>
                        <a href="{{ url_for('main.student_edit', id=student.id) }}"
                            class="btn btn-warning btn-sm float-end ms-2">Edit</a>
                    </td>
                    <td>
                        <a href="{{ url_for('main.student_destroy', id=student.id) }}"
                            class="btn btn-danger btn-sm float-end">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

app/templates/pages/teacher/create.html
{% extends 'index.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.teacher') }}" class="btn btn-secondary btn-sm">Back teachers</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Edit a teacher</h2>

    <form class="w-50 m-auto" method="POST" action="{{ url_for('main.teacher_create') }}" novalidate>
        {{ form.hidden_tag() }}

        {% include 'pages/teacher/form.html' %}

    </form>
</div>


{% endblock %}

app/templates/pages/teacher/edit.html
{% extends 'index.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}

<div class="my-5">

    <div class="d-grid gap-2 mb-2 d-md-block">
        <a href="{{ url_for('main.teacher') }}" class="btn btn-secondary btn-sm">Back teachers</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Edit a teacher</h2>

    <form class="m-auto" method="POST" action="{{ url_for('main.teacher_edit', id=teacher.id) }}" novalidate>

        {{ form.hidden_tag() }}

        {% include 'pages/teacher/form.html' %}

    </form>

</div>


{% endblock %}

app/templates/pages/teacher/index.html
{% extends 'index.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}

<div class="container my-5">

    <div class="d-grid gap-2 d-md-block">
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary btn-sm">Back home page</a>
        <a href="{{ url_for('main.teacher_create') }}" class="btn btn-primary btn-sm">Create a new teacher</a>
    </div>

    <h2 class="mb-3 text-center text-body-emphasis">Registered teachers</h2>

    <div class="table-responsive">
        <table id="table" class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Registration</th>
                    <th scope="col">Date of birth</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Address</th>
                    <th scope="col">Phone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">teachers</th>
                    <th scope="col">Courses</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                <tr>
                    <th scope="row">{{ teacher.id }}</th>
                    <td>{{ teacher.name }}</td>
                    <td>{{ teacher.registration }}</td>
                    <td>{{ teacher.date_of_birth }}</td>
                    <td>{{ teacher.gender }}</td>
                    <td>{{ teacher.address }}</td>
                    <td>{{ teacher.phone }}</td>
                    <td>{{ teacher.email }}</td>
                    <td>
                        <div class="dropdown">
                            {% if teacher.courses|length == 0 %}
                            No disciplines
                            {% else %}
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Disciplines
                            </button>
                            <ul class="dropdown-menu">
                                {% for discipline in teacher.disciplines %}
                                <li><a class="dropdown-item" href="#">{{ discipline.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        {% if teacher.courses|length == 0 %}
                        No courses
                        {% else %}
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Courses
                            </button>
                            <ul class="dropdown-menu">
                                {% for course in teacher.courses %}
                                <li><a class="dropdown-item" href="#">{{ course.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url_for('main.teacher_edit', id=teacher.id) }}"
                            class="btn btn-warning btn-sm float-end ms-2">Edit</a>
                    </td>
                    <td>
                        <a href="{{ url_for('main.teacher_destroy', id=teacher.id) }}"
                            class="btn btn-danger btn-sm float-end">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}